name: Orthodox
version: '${project.version}'
main: orthodox.hyperhaxstudios.Orthodox
api-version: 1.19
authors: [ HyperHax ]
commands:
  fly:
    description: Toggles flying for the command sender
    usage: /fly
    aliases: f
    permission: fly
    permission-message: You do not have premission to use this command.
  menu:
    description: Opens Server Menu
    usage: /menu